//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wildblood.Tactics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SvgResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SvgResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wildblood.Tactics.SvgResource", typeof(SvgResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; viewBox=\&quot;0 0 24 24\&quot;&gt;&lt;title&gt;arrow-top-right-thin&lt;/title&gt;&lt;path d=\&quot;M11.93 5L14.76 7.83L5 17.59L6.42 19L16.18 9.25L19 12.07V5H11.93Z\&quot; /&gt;&lt;/svg&gt;&quot;.
        /// </summary>
        public static string ArrowHead {
            get {
                return ResourceManager.GetString("ArrowHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; viewBox=\&quot;0 0 24 24\&quot;&gt;&lt;title&gt;vector-curve&lt;/title&gt;&lt;path d=\&quot;M18.5,2A1.5,1.5 0 0,1 20,3.5A1.5,1.5 0 0,1 18.5,5C18.27,5 18.05,4.95 17.85,4.85L14.16,8.55L14.5,9C16.69,7.74 19.26,7 22,7L23,7.03V9.04L22,9C19.42,9 17,9.75 15,11.04A3.96,3.96 0 0,1 11.04,15C9.75,17 9,19.42 9,22L9.04,23H7.03L7,22C7,19.26 7.74,16.69 9,14.5L8.55,14.16L4.85,17.85C4.95,18.05 5,18.27 5,18.5A1.5,1.5 0 0,1 3.5,20A1.5,1.5 0 0,1 2,18.5A1.5,1.5 0 0,1 3.5,17C3.73,17 3.95,17.05 4.15,17.15L7.84,13.45C7.3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CurveIcon {
            get {
                return ResourceManager.GetString("CurveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg width=\&quot;24\&quot; height=\&quot;24\&quot; viewBox=\&quot;0 0 24 24\&quot; xmlns=\&quot;http://www.w3.org/2000/svg\&quot;&gt;\r\n  &lt;line x1=\&quot;2\&quot; y1=\&quot;22\&quot; x2=\&quot;22\&quot; y2=\&quot;2\&quot; stroke=\&quot;white\&quot; stroke-width=\&quot;2\&quot; stroke-dasharray=\&quot;4,2\&quot; /&gt;\r\n&lt;/svg&gt;\r\n&quot;.
        /// </summary>
        public static string DashedLine {
            get {
                return ResourceManager.GetString("DashedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg width=\&quot;24\&quot; height=\&quot;24\&quot; viewBox=\&quot;0 0 24 24\&quot; xmlns=\&quot;http://www.w3.org/2000/svg\&quot;&gt;\r\n  &lt;line x1=\&quot;2\&quot; y1=\&quot;22\&quot; x2=\&quot;22\&quot; y2=\&quot;2\&quot; stroke=\&quot;white\&quot; stroke-width=\&quot;2\&quot; stroke-linecap=\&quot;round\&quot; stroke-dasharray=\&quot;0.1,4\&quot; /&gt;\r\n&lt;/svg&gt;\r\n&quot;.
        /// </summary>
        public static string DottetLine {
            get {
                return ResourceManager.GetString("DottetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; height=\&quot;24px\&quot; viewBox=\&quot;0 -960 960 960\&quot; width=\&quot;24px\&quot; fill=\&quot;#e3e3e3\&quot;&gt;&lt;path d=\&quot;M690-240h190v80H610l80-80Zm-500 80-85-85q-23-23-23.5-57t22.5-58l440-456q23-24 56.5-24t56.5 23l199 199q23 23 23 57t-23 57L520-160H190Zm296-80 314-322-198-198-442 456 64 64h262Zm-6-240Z\&quot;/&gt;&lt;/svg&gt;&quot;.
        /// </summary>
        public static string EraserIcon {
            get {
                return ResourceManager.GetString("EraserIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; height=\&quot;24px\&quot; viewBox=\&quot;0 -960 960 960\&quot; width=\&quot;24px\&quot; fill=\&quot;#e3e3e3\&quot;&gt;&lt;path d=\&quot;M199-199q-9-9-9-21t9-21l520-520q9-9 21-9t21 9q9 9 9 21t-9 21L241-199q-9 9-21 9t-21-9Z\&quot;/&gt;&lt;/svg&gt;&quot;.
        /// </summary>
        public static string SolidLine {
            get {
                return ResourceManager.GetString("SolidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg width=\&quot;24\&quot; height=\&quot;24\&quot; viewBox=\&quot;0 0 24 24\&quot; xmlns=\&quot;http://www.w3.org/2000/svg\&quot;&gt;\r\n  &lt;!-- Diagonale Linie --&gt;\r\n  &lt;line x1=\&quot;2\&quot; y1=\&quot;22\&quot; x2=\&quot;22\&quot; y2=\&quot;2\&quot; stroke=\&quot;white\&quot; stroke-width=\&quot;2\&quot; stroke-linecap=\&quot;round\&quot; /&gt;\r\n\r\n  &lt;!-- Querlinie (90° zur Diagonale, also gedreht) --&gt;\r\n  &lt;line x1=\&quot;-3\&quot; y1=\&quot;0\&quot; x2=\&quot;3\&quot; y2=\&quot;0\&quot; stroke=\&quot;white\&quot; stroke-width=\&quot;2\&quot; stroke-linecap=\&quot;round\&quot;\r\n        transform=\&quot;translate(22 2) rotate(45)\&quot; /&gt;\r\n&lt;/svg&gt;\r\n&quot;.
        /// </summary>
        public static string StraightArrow {
            get {
                return ResourceManager.GetString("StraightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; viewBox=\&quot;0 0 24 24\&quot;&gt;&lt;title&gt;sword-cross&lt;/title&gt;&lt;path d=\&quot;M6.2,2.44L18.1,14.34L20.22,12.22L21.63,13.63L19.16,16.1L22.34,19.28C22.73,19.67 22.73,20.3 22.34,20.69L21.63,21.4C21.24,21.79 20.61,21.79 20.22,21.4L17,18.23L14.56,20.7L13.15,19.29L15.27,17.17L3.37,5.27V2.44H6.2M15.89,10L20.63,5.26V2.44H17.8L13.06,7.18L15.89,10M10.94,15L8.11,12.13L5.9,14.34L3.78,12.22L2.37,13.63L4.84,16.1L1.66,19.29C1.27,19.68 1.27,20.31 1.66,20.7L2.37,21.41C2.76,21.8 3.39,21.8 3.78,21.41L7, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SwordsIcon {
            get {
                return ResourceManager.GetString("SwordsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; viewBox=\&quot;0 0 24 24\&quot;&gt;&lt;title&gt;vector-line&lt;/title&gt;&lt;path d=\&quot;M15,3V7.59L7.59,15H3V21H9V16.42L16.42,9H21V3M17,5H19V7H17M5,17H7V19H5\&quot; /&gt;&lt;/svg&gt;&quot;.
        /// </summary>
        public static string VectorLineIcon {
            get {
                return ResourceManager.GetString("VectorLineIcon", resourceCulture);
            }
        }
    }
}
