name: ci

on:
  push:
    branches: 
    - main
    - release/*

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
