namespace Wildblood.Tactics.Models.Tools;

using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum IconType
{
    Azaps,
    BlueShields,
    CamelLancers,
    Claymores,
    Cocos,
    DaggerAxeLancers,
    DemenseSpearmen,
    Falconetti,
    Fortes,
    HalberdierSergeant,
    Halberdiers,
    Hussars,
    ImperialArquebusiers,
    ImperialPikeMen,
    ImperialSpearGuard,
    IronReaper,
    IroncapScouts,
    JavSergeants,
    Kriegsbruders,
    Lionroarcrew,
    MaceSergeants,
    Martes,
    MenAtArms,
    Modao,
    Monastics,
    Myrmillos,
    Namkahn,
    OnnaMusha,
    OrochiSamurai,
    Outrider,
    PalaceGuards,
    Percevals,
    PrefectureGuards,
    PrefecturePikemen,
    QueensKnights,
    RattanArchers,
    RattanMarksmen,
    RattanPikemen,
    Selemchids,
    Shenji,
    Siladars,
    Siphonarioi,
    SonsOfFenrir,
    SunwardPhalanx,
    WuweiPikes,
    WuxingPikemen,
    Xuanjia,
    YanyuedaoCavalry,
    Zweihander,
}
